version: '3.0'
services:

  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    #image: mongo:latest
    image: mongo:3.6.15
    restart: on-failure
    container_name: mongodb

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    restart: always
    container_name: elasticsearch
    #hostname: elasticsearch
    environment:
      - cluster.name=graylog-cluster
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      #- ./es_config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
      - 9300:9300

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.2
    container_name: graylog
    hostname: graylog
    environment:
      - GRAYLOG_ROOT_TIMEZONE=Asia/Seoul
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.100.17:9000/
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      #- /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
      - ./graylog_journal:/usr/share/graylog/data/graylog_journal
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP/UDP
      - 8514:8514
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

